const koaRouter = require('koa-router')
const gameRoundController = require('../CONTROLLER/gameRoundController')
const gameRoundPolicy = require('../CONTROLLERPOLICY/gameRoundPolicy')
const router = new koaRouter()
//router.get('/getallrounds', gameRoundController.getAllRounds)
router.put('/rounds', gameRoundController.getRounds)
router.put('/create', gameRoundController.createRound)
router.delete('/*', gameRoundController.deleteRound)
router.get('/start/*', gameRoundPolicy.startRound, gameRoundController.startRound)
router.get('/getallplayerscore/*', gameRoundController.getRoundAllPlayersScore)
router.put('/state', gameRoundController.updateRoundState)
router.get('/state/*', gameRoundController.getRoundState)
router.get('/done/*', gameRoundController.setRoundDone)
module.exports = router