const koaRouter = require('koa-router')
const gameRoundController = require('../CONTROLLER/gameRoundController')
const gameRoundPolicy = require('../CONTROLLERPOLICY/gameRoundPolicy')
const router = new koaRouter()
router.get('/getallrounds', gameRoundController.getAllRounds)
router.put('/create', gameRoundController.createRound)
router.delete('/*', gameRoundController.deleteRound)
router.get('/start/*', gameRoundPolicy.startRound, gameRoundController.startRound)
router.get('/getallplayerscore/*', gameRoundController.getRoundAllPlayersScore)
module.exports = router